spring.application.name=thinktionary-backend

## POSTGRESSQL Database Connection Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/ThinktionaryDB
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update